server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /redirect-to-loopback {
        return 302 http://127.0.0.1:80/hello.html;
    }

    location / {
        try_files $uri =404;
    }
}
