import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import openapiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  sidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "API",
      items: openapiSidebar,
    },
  ],
};

export default sidebars;
